# Generated by Django 4.0.4 on 2022-08-12 14:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBTyp',
            fields=[
                ('nm', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SchedulerLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=80, unique=True)),
                ('prnt_uid', models.CharField(max_length=80)),
                ('pid', models.BigIntegerField(default=-9999)),
                ('user_data', models.CharField(default='', max_length=3200)),
                ('prirty', models.BigIntegerField(default=-9999)),
                ('file_pth', models.CharField(max_length=3200)),
                ('status', models.CharField(max_length=80)),
                ('crt_ts', models.DateTimeField(verbose_name='date created')),
                ('updt_ts', models.DateTimeField(verbose_name='date updated')),
            ],
        ),
        migrations.CreateModel(
            name='SchedulerProcess',
            fields=[
                ('pid', models.BigIntegerField(unique=True)),
                ('uid', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('tag', models.CharField(default='', max_length=80, unique=True)),
                ('status', models.CharField(default='', max_length=80)),
                ('crt_ts', models.DateTimeField(default=datetime.datetime(2022, 8, 12, 19, 42, 57, 73442), verbose_name='date created')),
                ('updt_ts', models.DateTimeField(default=datetime.datetime(2022, 8, 12, 19, 42, 57, 73442), verbose_name='date updated')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm', models.CharField(max_length=80)),
                ('val', models.CharField(max_length=3200)),
                ('crt_ts', models.DateTimeField(verbose_name='date created')),
                ('updt_ts', models.DateTimeField(verbose_name='date updated')),
                ('typ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.dbtyp')),
            ],
            options={
                'unique_together': {('typ', 'nm')},
            },
        ),
    ]
