# Generated by Django 4.0.4 on 2022-08-19 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulerload',
            name='pid',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='schedulerprocess',
            name='crt_ts',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 19, 14, 59, 36, 440331), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='schedulerprocess',
            name='updt_ts',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 19, 14, 59, 36, 440331), verbose_name='date updated'),
        ),
        migrations.CreateModel(
            name='SchedulerConnectConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vndr_nm', models.CharField(max_length=30)),
                ('prdct_typ', models.CharField(max_length=30)),
                ('prdct_nm', models.CharField(max_length=30)),
                ('prdct_ver', models.CharField(max_length=30)),
                ('cnnct_dir', models.CharField(max_length=3200)),
                ('cnnct_strng', models.CharField(max_length=3200)),
                ('crt_ts', models.DateTimeField(default=datetime.datetime(2022, 8, 19, 14, 59, 36, 439328), verbose_name='date created')),
                ('updt_ts', models.DateTimeField(default=datetime.datetime(2022, 8, 19, 14, 59, 36, 439328), verbose_name='date updated')),
            ],
            options={
                'unique_together': {('vndr_nm', 'prdct_typ', 'prdct_nm', 'prdct_ver')},
            },
        ),
    ]
