# Generated by Django 4.1 on 2022-08-26 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_schedulerprocess_cnnct_id_schedulerprocess_tmplt_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulerprocess',
            name='cnnct_cntxt',
            field=models.CharField(default='', max_length=32000),
        ),
        migrations.AlterField(
            model_name='schedulerconnectconfig',
            name='crt_ts',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 19, 58, 20, 431016), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='schedulerconnectconfig',
            name='updt_ts',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 19, 58, 20, 431016), verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='schedulerprocess',
            name='crt_ts',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 19, 58, 20, 432015), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='schedulerprocess',
            name='updt_ts',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 19, 58, 20, 432015), verbose_name='date updated'),
        ),
    ]
